columns:
  - id: int64
  - Gender: obejct 
  - Customer Type: object 
  - Age: int64
  - Type of Travel: object
  - Class: object
  - Flight Distance: int64
  - Inflight wifi service: int64 
  - Departure/Arrival time convenient: int64  
  - Ease of Online booking: int64
  - Gate location: int64 
  - Food and drink: int64  
  - Online boarding: int64
  - Seat comfort: int64 
  - Inflight entertainment: int64 
  - On-board service: int64 
  - Leg room service: int64
  - Baggage handling: int64 
  - Checkin service: int64
  - Inflight service: int64 
  - Cleanliness: int64
  - Departure Delay in minutes: int64  
  - Arrival Delay in Minutes: float64
  - satisfaction: object

numerical_columns:
  - id
  - Age
  - Flight Distance
  - Inflight wifi service
  - Departure/Arrival time convenient
  - Ease of Online booking
  - Gate location
  - Food and drink
  - Online boarding
  - Seat comfort
  - Inflight entertainment
  - On-board service
  - Leg room service
  - Baggage handling
  - Checkin service
  - Inflight service
  - Cleanliness
  - Departure Delay in Minutes
  - Arrival Delay in Minutes

categorical_columns:
  - Gender
  - Customer Type
  - Type of Travel
  - Class
  - satisfaction

drop_columns:
  - Unnamed: 0
  